[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Fabio Carpinato <fabiocarpinato@outlook.it>"]

[[bin]]
name = "example-server"
path = "src/bin/main.rs"

[[bench]]
name = "ping_benchmark"

[dependencies]
slab = "0.4.9"

