[package]
name = "server"
version = "0.1.0"
edition = "2021"
authors = ["Fabio Carpinato <fabiocarpinato@outlook.it>"]

[[bin]]
name = "example-server"
path = "src/bin/main.rs"

[[bench]]
name = "ping_benchmark"

[dependencies]
arraydeque = "0.5.1"
io-uring = "0.7.4"
nix = { version = "0.29.0", features = ["event", "poll"] }
slab = "0.4.9"

