[package]
name = "cli"
version = "0.1.0"
edition = "2021"
authors = ["Fabio Carpinato <fabiocarpinato@outlook.it>"]

[[bin]]
name = "cli"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.28", features = ["derive"] }
color-eyre = "0.6.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-input = "0.11.1"


